version: '3.3'
services:
  omada-controller:
    container_name: omada-controller
    image: 'mbentley/omada-controller:5.9'
    restart: unless-stopped
    network_mode: bridge
    ports:
      - '8088:8088'
      - '8043:8043'
      - '8843:8843'
      - '29810:29810/udp'
      - '29811:29811'
      - '29812:29812'
      - '29813:29813'
      - '29814:29814'
    environment:
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=America/Mexico_City
      - TLS_1_11_ENABLED=true
    volumes:
      - './omada-data:/opt/tplink/EAPController/data'
      - './omada-work:/opt/tplink/EAPController/work'
      - './omada-logs:/opt/tplink/EAPController/logs'
      - './omada-cert:/cert'
